services:
  db:
    image: postgres:13
    container_name: trackcore_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trackcore_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid && 
              mkdir -p tmp/pids &&
              chmod -R 777 tmp log &&
              bundle exec rails server -b '0.0.0.0' -P tmp/pids/server.pid"
    container_name: trackcore_app
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
      RAILS_LOG_TO_STDOUT: 'true'
      BINDING: '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app:cached
      - bundle_cache:/usr/local/bundle
      - tmp_data:/app/tmp
      - log_data:/app/log

volumes:
  pgdata:
  redis_data:
  bundle_cache:
  tmp_data:
  log_data:

networks:
  default:
    driver: bridge
