default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DB_USER", "trackcore") %>
  password: <%= ENV.fetch("DB_PASSWORD", "secret123") %>
  host: <%= ENV.fetch("DB_HOST", "db") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>

development:
  <<: *default
  database: trackcore_development

test:
  <<: *default
  database: trackcore_test

production:
  <<: *default
  database: trackcore_production
